# Generated by Django 3.2.3 on 2021-06-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210628_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('rut', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Rut')),
                ('nombreCompleto', models.CharField(max_length=100, verbose_name='NombreCompleto')),
                ('correoElectronico', models.CharField(max_length=50, verbose_name='CorreoElectronico')),
                ('region', models.CharField(max_length=30, verbose_name='Region')),
                ('ciudad', models.CharField(max_length=30, verbose_name='Ciudad')),
                ('texto', models.TextField(max_length=50, verbose_name='Texto')),
            ],
        ),
    ]
