# Generated by Django 3.2.3 on 2021-06-29 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='texto',
            field=models.TextField(max_length=200, verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=50, verbose_name='Password'),
        ),
    ]
