# Generated by Django 3.2.3 on 2021-06-29 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='correoElectronico',
            field=models.CharField(max_length=50, verbose_name='Correo Electronico'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombreCompleto',
            field=models.CharField(max_length=100, verbose_name='Nombre Completo'),
        ),
    ]
