# Generated by Django 3.2.3 on 2021-06-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210629_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombreObra',
            field=models.CharField(max_length=100, verbose_name='Nombre Obra'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='rut',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Rut'),
        ),
    ]
